src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtistRepository::class)
 */
class Artist
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=5000, nullable=true)
     */
    private ?string $display_name = null;

    /**
     * @ORM\Column(type="string", length=5000, nullable=true)
     */
    private ?string $begin_date = null;

    /**
     * @ORM\Column(type="string", length=5000, nullable=true)
     */
    private ?string $end_date = null;

    /**
     * @ORM\Column(type="string", length=5000, nullable=true)
     */
    private ?string $gender = null;

    /**
     * @ORM\Column(type="string", length=5000, nullable=true)
     */
    private ?string $nationality = null;

    /**
     * @ORM\OneToMany(targetEntity=Artwork::class, mappedBy="artist")
     */
    private $artworks;

    public function __construct(
        string $display_name = "",
        string $begin_date = "",
        string $end_date = "",
        string $gender = "",
        string $nationality = ""
    ) {
        $this->display_name = $display_name;
        $this->begin_date = $begin_date;
        $this->end_date = $end_date;
        $this->gender = $gender;
        $this->nationality = $nationality;
        $this->artworks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(?string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    public function getBeginDate(): ?string
    {
        return $this->begin_date;
    }

    public function setBeginDate(?string $begin_date): self
    {
        $this->begin_date = $begin_date;

        return $this;
    }

    public function getEndDate(): ?string
    {
        return $this->end_date;
    }

    public function setEndDate(?string $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(?string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function __toString(): string
    {
        return "name : " . $this->display_name;
    }

    /**
     * @return Collection|Artwork[]
     */
    public function getArtworks(): Collection
    {
        return $this->artworks;
    }

    public function addArtwork(Artwork $artwork): self
    {
        if (!$this->artworks->contains($artwork)) {
            $this->artworks[] = $artwork;
            $artwork->setArtist($this);
        }

        return $this;
    }

    public function removeArtwork(Artwork $artwork): self
    {
        if ($this->artworks->removeElement($artwork)) {
            // set the owning side to null (unless already changed)
            if ($artwork->getArtist() === $this) {
                $artwork->setArtist(null);
            }
        }

        return $this;
    }
}

src/Form/ArtistType.php
<?php

namespace App\Form;

use App\Entity\Artist;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtistType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('display_name')
            ->add('begin_date')
            ->add('end_date')
            ->add('gender')
            ->add('nationality')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Artist::class,
        ]);
    }
}

src/Controller/ArtistController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Repository\ArtistRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\Artist;
use App\Form\ArtistType;
use App\Data\SearchData;
use App\Form\SearchArtistType;

class ArtistController extends AbstractController
{
    /**
     * @Route("/artist", name="all_artist")
     */
    public function index(
        ArtistRepository $repository,
        string $deleteMessage = null,
        Request $request,
        PaginatorInterface $paginator
    ): Response {
        $searchArtistData = new SearchData();
        $searchArtistData->page = $request->get('page', 1);
        $form = $this->createForm(SearchArtistType::class, $searchArtistData);
        $form->handleRequest($request);
        $data = $repository->findSearch($searchArtistData);

        if (isset($_GET['deleteMessage']) && !empty($_GET['deleteMessage'])) {
            $deleteMessage = htmlspecialchars($_GET['deleteMessage']);
        }

        $artistColumns = array(
            "Display Name",
            "Begin Date",
            "End Date",
            "Gender",
            "Nationality",
        );

        $artists = $paginator->paginate(
            $data,
            $searchArtistData->page,
            50
        );

        return $this->render('artist/index.html.twig', [
            'artists' => $artists,
            'searchArtistForm' => $form->createView(),
            'length' => $artists->getTotalItemCount(),
            'artistColumns' => $artistColumns,
            'deleteMessage' => $deleteMessage,
        ]);
    }

    /**
     * @Route("/artist/{id}", name="one_artist", requirements={"id"= "[1-9]\d*"})
     */
    public function showArtist(ArtistRepository $repository, int $id, string $successMessage = null): Response
    {
        $artist = $repository->find($id);

        if ($artist == null) {
            //$message = "Artist not found";
            return $this->redirectToRoute('all_artist');
        }

        if ($artist->getArtworks() != null) {
            $length = $artist->getArtworks()->count();
        }

        if (isset($_GET['successMessage']) && !empty($_GET['successMessage'])) {
            $successMessage = htmlspecialchars($_GET['successMessage']);
        }

        return $this->render('artist/artist_show.html.twig', [
            'artist' => $artist,
            'length' => $length,
            'successMessage' => $successMessage
        ]);
    }

    /**
     * @Route("/artist/add", name="add_artist")
     */
    public function createArtist(ManagerRegistry $doctrine, Request $request): Response
    {
        $artist = new Artist();

        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artist = $form->getData();

            $entityManager = $doctrine->getManager();
            $entityManager->persist($artist);
            $entityManager->flush();

            $successMessage = "Artist created successfully !";

            return $this->redirectToRoute('one_artist', [
                'id' => $artist->getId(),
                'successMessage' => $successMessage
            ]);
        }

        return $this->render('artist/artist_form.html.twig', [
            'artistForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/artist/remove/{id}", name="remove_artist", requirements={"id"= "[1-9]\d*"})
     */
    public function removeArtist(ManagerRegistry $doctrine, int $id): RedirectResponse
    {
        $artist = $doctrine->getRepository(Artist::class)->find($id);

        if ($artist) {
            $entityManager = $doctrine->getManager();

            if ($artist->getArtworks() != null) {
                foreach ($artist->getArtworks() as $artwork) {
                    $entityManager->remove($artwork);
                }
            }

            $entityManager->remove($artist);
            $entityManager->flush();
            $deleteMessage = "Artist deleted successfully.";

            return $this->redirectToRoute('all_artist', ['deleteMessage' => $deleteMessage]);
        }

        return $this->redirectToRoute('all_artist');
    }

    /**
     * @Route("/artist/edit/{id}", name="edit_artist", requirements={"id"= "[1-9]\d*"})
     */
    public function editArtist(int $id, ManagerRegistry $doctrine, Request $request)
    {

        $artist = $doctrine->getRepository(Artist::class)->find($id);

        if ($artist) {

            $form = $this->createForm(ArtistType::class, $artist);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $artist = $form->getData();

                $entityManager = $doctrine->getManager();
                $entityManager->flush();
                $successMessage = "Artist changed successfully!";

                return $this->redirectToRoute('one_artist', [
                    'id' => $artist->getId(),
                    'successMessage' => $successMessage
                ]);
            }
            return $this->render('artist/edit_form.html.twig', [
                'artistEditForm' => $form->createView(),
            ]);
        }

        return $this->redirectToRoute('all_artist');
    }
}

templates/artist/artist_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Artist{% endblock %}

{% block body %}
    <div class="mt-3 container">
        <h4>Add Artist Form</h4>
        {{ form_start(artistForm) }}
            {% if form_errors(artistForm) is not empty %}
                {{ form_errors(artistForm) }}
            {% endif %}
            {{ form_row(artistForm.display_name) }}
            {{ form_row(artistForm.begin_date) }}
            {{ form_row(artistForm.end_date)}}
            {{ form_row(artistForm.gender)}}
            {{ form_row(artistForm.nationality)}}
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Create new artist !</button>
            </div>
        {{ form_end(artistForm) }}
    </div>
{% endblock %}

templates/artist/artist_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist show{% endblock %}

{% block body %}
    <div class="container">
        {% if successMessage is not empty %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ successMessage }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        
        {% if artist is not empty %}

            <div class="card mb-4 border-primary" style="width: 20rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ artist.displayName }}</h5>
                    <p class="card-text">{{ artist.displayName }} is of {{ artist.nationality }} nationality.</p>
                    <p class="card-text"><strong>gender</strong> : {{ artist.gender }}.</p>
                    <p class="card-text"><strong>begin date</strong> : {{ artist.getBeginDate }}, <strong>end date</strong> : {{ artist.getEndDate }}.</p>
                    <a class="btn btn-primary card-link" href="{{ path('edit_artist', {'id': artist.id}) }}" role="button">Edit this artist</a>
                    <a class="btn btn-danger card-link" href="{{ path('remove_artist', {'id': artist.id}) }}" role="button">Delete</a>
                </div>
            </div>

            {% if artist.artworks is not empty %}
                <h6 class="mt-4">Artist's artwork(s) :</h6>
                <p>This artist has made {{ length }} artwork(s).</p>
                <div class="container mt-4" style="display: flex; justify-content: space-evenly; flex-wrap: wrap;">
                    {% for artwork in artist.artworks %}
                        <div class="card mb-4 border-success" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ artwork.title }}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">{{ artwork.name }}</h6>
                                <p class="card-text">{{ artwork.classification }}</p>
                                <a href="{{ path('one_artwork', {'id': artwork.id}) }}" class="btn btn-success card-link" role="button">Show this artwork</a>
                                <a class="btn btn-danger card-link" href="{{ path('remove_artwork', {'id': artwork.id}) }}" role="button">Delete</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p> No artwork(s) to display about this artist.</p>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

templates/artist/edit_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Artist{% endblock %}

{% block body %}
    <div class="mt-3 container" style="background-color: #E5F1FF;">
        <h4>Edit Artist Form</h4>
        {{ form_start(artistEditForm) }}
            {% if form_errors(artistEditForm) is not empty %}
                {{ form_errors(artistEditForm) }}
            {% endif %}
            {{ form_row(artistEditForm.display_name) }}
            {{ form_row(artistEditForm.begin_date) }}
            {{ form_row(artistEditForm.end_date)}}
            {{ form_row(artistEditForm.gender)}}
            {{ form_row(artistEditForm.nationality)}}
            <div class="mt-3" style="display: flex; justify-content: space-evenly; flex-wrap: wrap;">
                <button type="submit" class="btn btn-primary">Modify artist !</button>
                <a class="btn btn-danger" role="button" href="{{ path('all_artist') }}">Cancel</a>
            </div>
        {{ form_end(artistEditForm) }}
    </div>
{% endblock %}

templates/artist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Artists{% endblock %}

{% block body %}
<div class="container">
    <h4 style="text-align: center;">{{ length }} artist(s) found</h4>
    {% if deleteMessage is not empty %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ deleteMessage }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <h6>Filter artist form : </h6>
    <p>You can search by filtering certain fields such as the <strong>artist's name</strong> or <strong>artist's gender</strong> for example.</p>

    {{ form_start(searchArtistForm) }}
        <div style="display: flex; justify-content: space-evenly; flex-wrap: wrap;">
            {{ form_row(searchArtistForm.display_name )}}
            {{ form_row(searchArtistForm.begin_date) }}
            {{ form_row(searchArtistForm.end_date) }}
            {{ form_row(searchArtistForm.gender) }}
            {{ form_row(searchArtistForm.nationality) }}
            {{ form_row(searchArtistForm.offset) }}
            {{ form_row(searchArtistForm.limit) }}
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Search !</button>
        </div>
    {{ form_end(searchArtistForm) }}

    <table class="table table-primary mt-4">
        <thead>
            <tr>
                <th scope="col"># id</th>
                {% for column in artistColumns %}
                    <th scope="col">{{ column }}</th>
                {% endfor %}
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for artist in artists %}
                <tr>
                    <th scope="row">{{ artist.id }}</th>
                    <td>{{ artist.getDisplayName }}</td>
                    <td>{{ artist.getBeginDate }}</td>
                    <td>{{ artist.getEndDate }}</td>
                    <td>{{ artist.gender }}</td>
                    <td>{{ artist.nationality }}</td>
                    <td><a class="btn btn-primary" href="{{ path('one_artist', {'id': artist.id}) }}" role="button">Show</a></td>
                    <td><a class="btn btn-danger" href="{{ path('remove_artist', {'id': artist.id}) }}" role="button">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="container-fluid mt-4" style="display: flex; justify-content: center;">
    {{ knp_pagination_render(artists, '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig') }}
</div>
{% endblock %}